add separator as second input, update script comment

diff --git a/empty_cells b/empty_cells
--- a/empty_cells
+++ b/empty_cells
@@ -1,19 +1,34 @@
 #!/bin/bash
 
-# 23884895 - Xuechen MAO
-# The script is used to count the number of empty cells in each column of a txt file
+# --------------------------------------------------------------------
+# Author: 23884895 - Xuechen MAO
+# Purpose: The script is used to count the number of empty cells in each column of a file, and the separator is provided as a second argument
+# Usage: ./empty_cells input_file.txt seperator, e.g. ./empty_cells file.txt ';'
+# --------------------------------------------------------------------
 
-# add first input as file
-file=$1
+# accept 2 arguments: input file and separator
+file="$1"
+separator="$2"
 
-# if no valid file, print error and exit
-if [ $# -ne 1 ]; then
-    echo "error: file does not exist. Please use a valid file" >&2 
+# 1. Check number of arguments, and print usage if not 2
+if [ $# -ne 2 ]; then
+    echo "Usage: ./empty_cells input_file.txt seperator" >&2
     exit 1
 fi
 
+# 2. Check if the first input - file exists
+if [ ! -f "$file" ]; then
+    echo "Error: File '$file' does not exist." >&2
+    exit 1
+fi
 
-awk -F';' '
+# 3. using header to check if the separator actually appears
+if [[ ! $(head -n 1 "$file") =~ "$separator" ]]; then
+    echo "Error: Separator '$separator' not found in the file." >&2
+    exit 1
+fi
+
+awk -F"$separator" '
 # process the 1st row -- header, and initialize the number to 0
 NR == 1 {
     sub(/\r$/, "")  # remove carriage return if present
